file:
  path: '_posts/{{ date | date: "%F" }}-{{ slug }}.md'
  content: |
    ---
    layout: post
    title: {{ subject }}
    ---
    {{ body }}
git:
  repo: test.git
  remote: origin
  email: mail2git@cplug.org
  name: mail2git
  message: 'post "{{ subject }}"'
